/*
 * ConsumerIam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.ConsumerIamClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.ConsumerIamClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.ConsumerIamClient.Model
{
    /// <summary>
    /// Defines RightsEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RightsEnum
    {
        /// <summary>
        /// Enum VfsRead for value: vfs-read
        /// </summary>
        [EnumMember(Value = "vfs-read")]
        VfsRead = 1,

        /// <summary>
        /// Enum VfsWrite for value: vfs-write
        /// </summary>
        [EnumMember(Value = "vfs-write")]
        VfsWrite = 2
    }

}
