/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// DTO contains authcrypted message in JSON fromat
    /// </summary>
    [DataContract(Name = "AuthcryptMessageResultDto")]
    public partial class AuthcryptMessageResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthcryptMessageResultDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthcryptMessageResultDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthcryptMessageResultDto" /> class.
        /// </summary>
        /// <param name="authcryptedMessage">Authcrypted message in JSON format (required).</param>
        public AuthcryptMessageResultDto(Object authcryptedMessage = default)
        {
            // to ensure "authcryptedMessage" is required (not null)
            if (authcryptedMessage == null)
            {
                throw new ArgumentNullException("authcryptedMessage is a required property for AuthcryptMessageResultDto and cannot be null");
            }
            this.AuthcryptedMessage = authcryptedMessage;
        }

        /// <summary>
        /// Authcrypted message in JSON format
        /// </summary>
        /// <value>Authcrypted message in JSON format</value>
        [DataMember(Name = "authcryptedMessage", IsRequired = true, EmitDefaultValue = true)]
        public Object AuthcryptedMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthcryptMessageResultDto {\n");
            sb.Append("  AuthcryptedMessage: ").Append(AuthcryptedMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
