/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// DTO contains revocation list credential
    /// </summary>
    [DataContract(Name = "GetRevocationCredentialStatusOK")]
    public partial class GetRevocationCredentialStatusOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRevocationCredentialStatusOK" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetRevocationCredentialStatusOK() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRevocationCredentialStatusOK" /> class.
        /// </summary>
        /// <param name="revocationListCredential">revocationListCredential (required).</param>
        public GetRevocationCredentialStatusOK(Object revocationListCredential = default)
        {
            // to ensure "revocationListCredential" is required (not null)
            if (revocationListCredential == null)
            {
                throw new ArgumentNullException("revocationListCredential is a required property for GetRevocationCredentialStatusOK and cannot be null");
            }
            this.RevocationListCredential = revocationListCredential;
        }

        /// <summary>
        /// Gets or Sets RevocationListCredential
        /// </summary>
        [DataMember(Name = "revocationListCredential", IsRequired = true, EmitDefaultValue = true)]
        public Object RevocationListCredential { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetRevocationCredentialStatusOK {\n");
            sb.Append("  RevocationListCredential: ").Append(RevocationListCredential).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
