/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// Response containing service endpoints
    /// </summary>
    [DataContract(Name = "ListServiceEndpointsOK")]
    public partial class ListServiceEndpointsOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListServiceEndpointsOK" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListServiceEndpointsOK() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListServiceEndpointsOK" /> class.
        /// </summary>
        /// <param name="services">list of service endpoints (required).</param>
        public ListServiceEndpointsOK(List<ServiceEndpointDto> services = default)
        {
            // to ensure "services" is required (not null)
            if (services == null)
            {
                throw new ArgumentNullException("services is a required property for ListServiceEndpointsOK and cannot be null");
            }
            this.Services = services;
        }

        /// <summary>
        /// list of service endpoints
        /// </summary>
        /// <value>list of service endpoints</value>
        [DataMember(Name = "services", IsRequired = true, EmitDefaultValue = true)]
        public List<ServiceEndpointDto> Services { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListServiceEndpointsOK {\n");
            sb.Append("  Services: ").Append(Services).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
