/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// Input for adding a service endpoint
    /// </summary>
    [DataContract(Name = "ServiceEndpointInput")]
    public partial class ServiceEndpointInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceEndpointInput" /> class.
        /// </summary>
        /// <param name="name">Name of the service endpoint.</param>
        /// <param name="description">Description of the service endpoint.</param>
        /// <param name="url">service endpoint URL.</param>
        /// <param name="serviceType">type of service endpoint.</param>
        public ServiceEndpointInput(string name = default, string description = default, string url = default, string serviceType = default)
        {
            this.Name = name;
            this.Description = description;
            this.Url = url;
            this.ServiceType = serviceType;
        }

        /// <summary>
        /// Name of the service endpoint
        /// </summary>
        /// <value>Name of the service endpoint</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the service endpoint
        /// </summary>
        /// <value>Description of the service endpoint</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// service endpoint URL
        /// </summary>
        /// <value>service endpoint URL</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// type of service endpoint
        /// </summary>
        /// <value>type of service endpoint</value>
        [DataMember(Name = "serviceType", EmitDefaultValue = false)]
        public string ServiceType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceEndpointInput {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  ServiceType: ").Append(ServiceType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 500.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 1.", new [] { "Description" });
            }

            // Url (string) maxLength
            if (this.Url != null && this.Url.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for Url, length must be less than 2048.", new [] { "Url" });
            }

            if (this.Url != null) {
                // Url (string) pattern
                Regex regexUrl = new Regex(@"^https?:\/\/.+", RegexOptions.CultureInvariant);
                if (!regexUrl.Match(this.Url).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Url, must match a pattern of " + regexUrl, new [] { "Url" });
                }
            }

            // ServiceType (string) maxLength
            if (this.ServiceType != null && this.ServiceType.Length > 100)
            {
                yield return new ValidationResult("Invalid value for ServiceType, length must be less than 100.", new [] { "ServiceType" });
            }

            yield break;
        }
    }

}
