/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// DID document verification relationship
    /// </summary>
    /// <value>DID document verification relationship</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VerificationRelationship
    {
        /// <summary>
        /// Enum Authentication for value: authentication
        /// </summary>
        [EnumMember(Value = "authentication")]
        Authentication = 1,

        /// <summary>
        /// Enum AssertionMethod for value: assertionMethod
        /// </summary>
        [EnumMember(Value = "assertionMethod")]
        AssertionMethod = 2,

        /// <summary>
        /// Enum KeyAgreement for value: keyAgreement
        /// </summary>
        [EnumMember(Value = "keyAgreement")]
        KeyAgreement = 3,

        /// <summary>
        /// Enum CapabilityInvocation for value: capabilityInvocation
        /// </summary>
        [EnumMember(Value = "capabilityInvocation")]
        CapabilityInvocation = 4,

        /// <summary>
        /// Enum CapabilityDelegation for value: capabilityDelegation
        /// </summary>
        [EnumMember(Value = "capabilityDelegation")]
        CapabilityDelegation = 5
    }

}
