/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.WalletsClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.WalletsClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.WalletsClient.Model
{
    /// <summary>
    /// DID method type for the wallet
    /// </summary>
    /// <value>DID method type for the wallet</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WalletDidType
    {
        /// <summary>
        /// Enum WEB for value: WEB
        /// </summary>
        [EnumMember(Value = "WEB")]
        WEB = 1,

        /// <summary>
        /// Enum KEY for value: KEY
        /// </summary>
        [EnumMember(Value = "KEY")]
        KEY = 2
    }

}
