/*
 * OidcVpAdapterBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using AffinidiTdk.LoginConfigurationClient.Client;
using AffinidiTdk.LoginConfigurationClient.Model;

namespace AffinidiTdk.LoginConfigurationClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDenyListApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns></returns>
        void BlockGroups(GroupNamesInput? groupNamesInput = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> BlockGroupsWithHttpInfo(GroupNamesInput? groupNamesInput = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns></returns>
        void BlockUsers(BlockedUsersInput? blockedUsersInput = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> BlockUsersWithHttpInfo(BlockedUsersInput? blockedUsersInput = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get Blocked Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>GroupNames</returns>
        GroupNames ListBlockedGroups(string? pageToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get Blocked Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>ApiResponse of GroupNames</returns>
        ApiResponse<GroupNames> ListBlockedGroupsWithHttpInfo(string? pageToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get List of Blocked Users
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>BlockedUsers</returns>
        BlockedUsers ListBlockedUsers(string? pageToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get List of Blocked Users
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>ApiResponse of BlockedUsers</returns>
        ApiResponse<BlockedUsers> ListBlockedUsersWithHttpInfo(string? pageToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns></returns>
        void UnblockGroups(GroupNamesInput? groupNamesInput = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UnblockGroupsWithHttpInfo(GroupNamesInput? groupNamesInput = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns></returns>
        void UnblockUsers(BlockedUsersInput? blockedUsersInput = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UnblockUsersWithHttpInfo(BlockedUsersInput? blockedUsersInput = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDenyListApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task BlockGroupsAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> BlockGroupsWithHttpInfoAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task BlockUsersAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Block Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> BlockUsersWithHttpInfoAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get Blocked Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GroupNames</returns>
        System.Threading.Tasks.Task<GroupNames> ListBlockedGroupsAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get Blocked Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GroupNames)</returns>
        System.Threading.Tasks.Task<ApiResponse<GroupNames>> ListBlockedGroupsWithHttpInfoAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get List of Blocked Users
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BlockedUsers</returns>
        System.Threading.Tasks.Task<BlockedUsers> ListBlockedUsersAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get List of Blocked Users
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BlockedUsers)</returns>
        System.Threading.Tasks.Task<ApiResponse<BlockedUsers>> ListBlockedUsersWithHttpInfoAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UnblockGroupsAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple Groups
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UnblockGroupsWithHttpInfoAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UnblockUsersAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Unblock Single or Multiple user ids
        /// </remarks>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UnblockUsersWithHttpInfoAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDenyListApi : IDenyListApiSync, IDenyListApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DenyListApi : IDisposable, IDenyListApi
    {
        private AffinidiTdk.LoginConfigurationClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DenyListApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DenyListApi(string basePath)
        {
            this.Configuration = AffinidiTdk.LoginConfigurationClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.LoginConfigurationClient.Client.GlobalConfiguration.Instance,
                new AffinidiTdk.LoginConfigurationClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AffinidiTdk.LoginConfigurationClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AffinidiTdk.LoginConfigurationClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DenyListApi(AffinidiTdk.LoginConfigurationClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AffinidiTdk.LoginConfigurationClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.LoginConfigurationClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AffinidiTdk.LoginConfigurationClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AffinidiTdk.LoginConfigurationClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DenyListApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DenyListApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AffinidiTdk.LoginConfigurationClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.LoginConfigurationClient.Client.GlobalConfiguration.Instance,
                new AffinidiTdk.LoginConfigurationClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AffinidiTdk.LoginConfigurationClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AffinidiTdk.LoginConfigurationClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DenyListApi(HttpClient client, AffinidiTdk.LoginConfigurationClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AffinidiTdk.LoginConfigurationClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.LoginConfigurationClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AffinidiTdk.LoginConfigurationClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AffinidiTdk.LoginConfigurationClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DenyListApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DenyListApi(AffinidiTdk.LoginConfigurationClient.Client.ISynchronousClient client, AffinidiTdk.LoginConfigurationClient.Client.IAsynchronousClient asyncClient, AffinidiTdk.LoginConfigurationClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AffinidiTdk.LoginConfigurationClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AffinidiTdk.LoginConfigurationClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AffinidiTdk.LoginConfigurationClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AffinidiTdk.LoginConfigurationClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AffinidiTdk.LoginConfigurationClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Block Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns></returns>
        public void BlockGroups(GroupNamesInput? groupNamesInput = default)
        {
            BlockGroupsWithHttpInfo(groupNamesInput);
        }

        /// <summary>
        ///  Block Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object> BlockGroupsWithHttpInfo(GroupNamesInput? groupNamesInput = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = groupNamesInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/deny-list/groups/add", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BlockGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Block Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task BlockGroupsAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await BlockGroupsWithHttpInfoAsync(groupNamesInput, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Block Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object>> BlockGroupsWithHttpInfoAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = groupNamesInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/deny-list/groups/add", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BlockGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Block Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns></returns>
        public void BlockUsers(BlockedUsersInput? blockedUsersInput = default)
        {
            BlockUsersWithHttpInfo(blockedUsersInput);
        }

        /// <summary>
        ///  Block Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object> BlockUsersWithHttpInfo(BlockedUsersInput? blockedUsersInput = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = blockedUsersInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/deny-list/users/add", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BlockUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Block Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task BlockUsersAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await BlockUsersWithHttpInfoAsync(blockedUsersInput, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Block Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object>> BlockUsersWithHttpInfoAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = blockedUsersInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/deny-list/users/add", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BlockUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get Blocked Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>GroupNames</returns>
        public GroupNames ListBlockedGroups(string? pageToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<GroupNames> localVarResponse = ListBlockedGroupsWithHttpInfo(pageToken);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get Blocked Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>ApiResponse of GroupNames</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<GroupNames> ListBlockedGroupsWithHttpInfo(string? pageToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GroupNames>("/v1/deny-list/groups", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBlockedGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get Blocked Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GroupNames</returns>
        public async System.Threading.Tasks.Task<GroupNames> ListBlockedGroupsAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<GroupNames> localVarResponse = await ListBlockedGroupsWithHttpInfoAsync(pageToken, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get Blocked Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GroupNames)</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<GroupNames>> ListBlockedGroupsWithHttpInfoAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GroupNames>("/v1/deny-list/groups", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBlockedGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get List of Blocked Users
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>BlockedUsers</returns>
        public BlockedUsers ListBlockedUsers(string? pageToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<BlockedUsers> localVarResponse = ListBlockedUsersWithHttpInfo(pageToken);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get List of Blocked Users
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <returns>ApiResponse of BlockedUsers</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<BlockedUsers> ListBlockedUsersWithHttpInfo(string? pageToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BlockedUsers>("/v1/deny-list/users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBlockedUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get List of Blocked Users
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BlockedUsers</returns>
        public async System.Threading.Tasks.Task<BlockedUsers> ListBlockedUsersAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<BlockedUsers> localVarResponse = await ListBlockedUsersWithHttpInfoAsync(pageToken, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get List of Blocked Users
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BlockedUsers)</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<BlockedUsers>> ListBlockedUsersWithHttpInfoAsync(string? pageToken = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<BlockedUsers>("/v1/deny-list/users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBlockedUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Unblock Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns></returns>
        public void UnblockGroups(GroupNamesInput? groupNamesInput = default)
        {
            UnblockGroupsWithHttpInfo(groupNamesInput);
        }

        /// <summary>
        ///  Unblock Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object> UnblockGroupsWithHttpInfo(GroupNamesInput? groupNamesInput = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = groupNamesInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/deny-list/groups/remove", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnblockGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Unblock Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UnblockGroupsAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await UnblockGroupsWithHttpInfoAsync(groupNamesInput, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Unblock Single or Multiple Groups
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupNamesInput">List of group names as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object>> UnblockGroupsWithHttpInfoAsync(GroupNamesInput? groupNamesInput = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = groupNamesInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/deny-list/groups/remove", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnblockGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Unblock Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns></returns>
        public void UnblockUsers(BlockedUsersInput? blockedUsersInput = default)
        {
            UnblockUsersWithHttpInfo(blockedUsersInput);
        }

        /// <summary>
        ///  Unblock Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object> UnblockUsersWithHttpInfo(BlockedUsersInput? blockedUsersInput = default)
        {
            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = blockedUsersInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/deny-list/users/remove", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnblockUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Unblock Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UnblockUsersAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await UnblockUsersWithHttpInfoAsync(blockedUsersInput, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Unblock Single or Multiple user ids
        /// </summary>
        /// <exception cref="AffinidiTdk.LoginConfigurationClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blockedUsersInput">List of blocked users as input (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.LoginConfigurationClient.Client.ApiResponse<Object>> UnblockUsersWithHttpInfoAsync(BlockedUsersInput? blockedUsersInput = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AffinidiTdk.LoginConfigurationClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.LoginConfigurationClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.LoginConfigurationClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = blockedUsersInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/deny-list/users/remove", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnblockUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
