/*
 * CredentialIssuanceService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.CredentialIssuanceClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.CredentialIssuanceClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.CredentialIssuanceClient.Model
{
    /// <summary>
    /// BatchCredentialResponseCredentialResponsesInner
    /// </summary>
    [DataContract(Name = "BatchCredentialResponse_credential_responses_inner")]
    public partial class BatchCredentialResponseCredentialResponsesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCredentialResponseCredentialResponsesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchCredentialResponseCredentialResponsesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCredentialResponseCredentialResponsesInner" /> class.
        /// </summary>
        /// <param name="credential">Issued Credential, It can be a string or an object, depending on the Credential format. default format  is &#x60;ldp_vc&#x60;. (required).</param>
        public BatchCredentialResponseCredentialResponsesInner(Object credential = default)
        {
            // to ensure "credential" is required (not null)
            if (credential == null)
            {
                throw new ArgumentNullException("credential is a required property for BatchCredentialResponseCredentialResponsesInner and cannot be null");
            }
            this.Credential = credential;
        }

        /// <summary>
        /// Issued Credential, It can be a string or an object, depending on the Credential format. default format  is &#x60;ldp_vc&#x60;.
        /// </summary>
        /// <value>Issued Credential, It can be a string or an object, depending on the Credential format. default format  is &#x60;ldp_vc&#x60;.</value>
        [DataMember(Name = "credential", IsRequired = true, EmitDefaultValue = true)]
        public Object Credential { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchCredentialResponseCredentialResponsesInner {\n");
            sb.Append("  Credential: ").Append(Credential).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
