/*
 * CredentialIssuanceService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.CredentialIssuanceClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.CredentialIssuanceClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.CredentialIssuanceClient.Model
{
    /// <summary>
    /// List of claimed credential
    /// </summary>
    [DataContract(Name = "ClaimedCredentialListResponse")]
    public partial class ClaimedCredentialListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClaimedCredentialListResponse" /> class.
        /// </summary>
        /// <param name="credentials">list of credentials.</param>
        /// <param name="lastEvaluatedKey">for pagination to fetch next set of records.</param>
        public ClaimedCredentialListResponse(List<Dictionary<string, Object>> credentials = default, string lastEvaluatedKey = default)
        {
            this.Credentials = credentials;
            this.LastEvaluatedKey = lastEvaluatedKey;
        }

        /// <summary>
        /// list of credentials
        /// </summary>
        /// <value>list of credentials</value>
        [DataMember(Name = "credentials", EmitDefaultValue = false)]
        public List<Dictionary<string, Object>> Credentials { get; set; }

        /// <summary>
        /// for pagination to fetch next set of records
        /// </summary>
        /// <value>for pagination to fetch next set of records</value>
        [DataMember(Name = "lastEvaluatedKey", EmitDefaultValue = false)]
        public string LastEvaluatedKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClaimedCredentialListResponse {\n");
            sb.Append("  Credentials: ").Append(Credentials).Append("\n");
            sb.Append("  LastEvaluatedKey: ").Append(LastEvaluatedKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
