/*
 * VerificationService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.CredentialVerificationClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.CredentialVerificationClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.CredentialVerificationClient.Model
{
    /// <summary>
    /// PdStatus
    /// </summary>
    [DataContract(Name = "PdStatus")]
    public partial class PdStatus : IValidatableObject
    {
        /// <summary>
        /// Defines Directive
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DirectiveEnum
        {
            /// <summary>
            /// Enum Required for value: required
            /// </summary>
            [EnumMember(Value = "required")]
            Required = 1,

            /// <summary>
            /// Enum Allowed for value: allowed
            /// </summary>
            [EnumMember(Value = "allowed")]
            Allowed = 2,

            /// <summary>
            /// Enum Disallowed for value: disallowed
            /// </summary>
            [EnumMember(Value = "disallowed")]
            Disallowed = 3
        }


        /// <summary>
        /// Gets or Sets Directive
        /// </summary>
        [DataMember(Name = "directive", EmitDefaultValue = false)]
        public DirectiveEnum? Directive { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PdStatus" /> class.
        /// </summary>
        /// <param name="directive">directive.</param>
        public PdStatus(DirectiveEnum? directive = default)
        {
            this.Directive = directive;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PdStatus {\n");
            sb.Append("  Directive: ").Append(Directive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
