/*
 * VerificationService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.CredentialVerificationClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.CredentialVerificationClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.CredentialVerificationClient.Model
{
    /// <summary>
    /// Presentation Exchange Query containing presentation definition and submission
    /// </summary>
    [DataContract(Name = "VerifyPresentationV2Input_pexQuery")]
    public partial class VerifyPresentationV2InputPexQuery : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyPresentationV2InputPexQuery" /> class.
        /// </summary>
        /// <param name="presentationDefinition">Presentation definition for the verification request.</param>
        /// <param name="presentationSubmission">Presentation submission for the verification request.</param>
        public VerifyPresentationV2InputPexQuery(Object presentationDefinition = default, Object presentationSubmission = default)
        {
            this.PresentationDefinition = presentationDefinition;
            this.PresentationSubmission = presentationSubmission;
        }

        /// <summary>
        /// Presentation definition for the verification request
        /// </summary>
        /// <value>Presentation definition for the verification request</value>
        [DataMember(Name = "presentationDefinition", EmitDefaultValue = false)]
        public Object PresentationDefinition { get; set; }

        /// <summary>
        /// Presentation submission for the verification request
        /// </summary>
        /// <value>Presentation submission for the verification request</value>
        [DataMember(Name = "presentationSubmission", EmitDefaultValue = false)]
        public Object PresentationSubmission { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyPresentationV2InputPexQuery {\n");
            sb.Append("  PresentationDefinition: ").Append(PresentationDefinition).Append("\n");
            sb.Append("  PresentationSubmission: ").Append(PresentationSubmission).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
