/*
 * Iam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.IamClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.IamClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.IamClient.Model
{
    /// <summary>
    /// CorsUpdateAccessVfsOK
    /// </summary>
    [DataContract(Name = "CorsUpdateAccessVfsOK")]
    public partial class CorsUpdateAccessVfsOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorsUpdateAccessVfsOK" /> class.
        /// </summary>
        /// <param name="corsUpdateAccessVfsOk">corsUpdateAccessVfsOk.</param>
        public CorsUpdateAccessVfsOK(string corsUpdateAccessVfsOk = default)
        {
            this.CorsUpdateAccessVfsOk = corsUpdateAccessVfsOk;
        }

        /// <summary>
        /// Gets or Sets CorsUpdateAccessVfsOk
        /// </summary>
        [DataMember(Name = "corsUpdateAccessVfsOk", EmitDefaultValue = false)]
        public string CorsUpdateAccessVfsOk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CorsUpdateAccessVfsOK {\n");
            sb.Append("  CorsUpdateAccessVfsOk: ").Append(CorsUpdateAccessVfsOk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
