/*
 * Iam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.IamClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.IamClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.IamClient.Model
{
    /// <summary>
    /// ProjectList
    /// </summary>
    [DataContract(Name = "ProjectList")]
    public partial class ProjectList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectList" /> class.
        /// </summary>
        /// <param name="projects">projects (required).</param>
        /// <param name="lastEvaluatedKey">lastEvaluatedKey.</param>
        public ProjectList(List<ProjectDto> projects = default, string lastEvaluatedKey = default)
        {
            // to ensure "projects" is required (not null)
            if (projects == null)
            {
                throw new ArgumentNullException("projects is a required property for ProjectList and cannot be null");
            }
            this.Projects = projects;
            this.LastEvaluatedKey = lastEvaluatedKey;
        }

        /// <summary>
        /// Gets or Sets Projects
        /// </summary>
        [DataMember(Name = "projects", IsRequired = true, EmitDefaultValue = true)]
        public List<ProjectDto> Projects { get; set; }

        /// <summary>
        /// Gets or Sets LastEvaluatedKey
        /// </summary>
        [DataMember(Name = "lastEvaluatedKey", EmitDefaultValue = false)]
        public string LastEvaluatedKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectList {\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("  LastEvaluatedKey: ").Append(LastEvaluatedKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
