/*
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.VaultDataManagerClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.VaultDataManagerClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.VaultDataManagerClient.Model
{
    /// <summary>
    /// A base64 encoded data encryption key, encrypted with consumer DEKEK, required for node types [FILE, PROFILE]
    /// </summary>
    [DataContract(Name = "EdekInfo")]
    public partial class EdekInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdekInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdekInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdekInfo" /> class.
        /// </summary>
        /// <param name="edek">edek (required).</param>
        /// <param name="dekekId">dekekId (required).</param>
        public EdekInfo(string edek = default, string dekekId = default)
        {
            // to ensure "edek" is required (not null)
            if (edek == null)
            {
                throw new ArgumentNullException("edek is a required property for EdekInfo and cannot be null");
            }
            this.Edek = edek;
            // to ensure "dekekId" is required (not null)
            if (dekekId == null)
            {
                throw new ArgumentNullException("dekekId is a required property for EdekInfo and cannot be null");
            }
            this.DekekId = dekekId;
        }

        /// <summary>
        /// Gets or Sets Edek
        /// </summary>
        [DataMember(Name = "edek", IsRequired = true, EmitDefaultValue = true)]
        public string Edek { get; set; }

        /// <summary>
        /// Gets or Sets DekekId
        /// </summary>
        [DataMember(Name = "dekekId", IsRequired = true, EmitDefaultValue = true)]
        public string DekekId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdekInfo {\n");
            sb.Append("  Edek: ").Append(Edek).Append("\n");
            sb.Append("  DekekId: ").Append(DekekId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
