/*
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.VaultDataManagerClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.VaultDataManagerClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.VaultDataManagerClient.Model
{
    /// <summary>
    /// ListNodeChildrenOK
    /// </summary>
    [DataContract(Name = "ListNodeChildrenOK")]
    public partial class ListNodeChildrenOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListNodeChildrenOK" /> class.
        /// </summary>
        /// <param name="nodes">nodes.</param>
        /// <param name="lastEvaluatedKey">lastEvaluatedKey.</param>
        public ListNodeChildrenOK(List<NodeDto> nodes = default, string lastEvaluatedKey = default)
        {
            this.Nodes = nodes;
            this.LastEvaluatedKey = lastEvaluatedKey;
        }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [DataMember(Name = "nodes", EmitDefaultValue = false)]
        public List<NodeDto> Nodes { get; set; }

        /// <summary>
        /// Gets or Sets LastEvaluatedKey
        /// </summary>
        [DataMember(Name = "lastEvaluatedKey", EmitDefaultValue = false)]
        public string LastEvaluatedKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListNodeChildrenOK {\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("  LastEvaluatedKey: ").Append(LastEvaluatedKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
