/*
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.VaultDataManagerClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.VaultDataManagerClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.VaultDataManagerClient.Model
{
    /// <summary>
    /// StartFileScanInput
    /// </summary>
    [DataContract(Name = "StartFileScanInput")]
    public partial class StartFileScanInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StartFileScanInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StartFileScanInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartFileScanInput" /> class.
        /// </summary>
        /// <param name="dek">A base64 encoded data encryption key, encrypted using VFS public key. This is important as this is used when starting document scan and also while uploading the file to s3 (required).</param>
        public StartFileScanInput(string dek = default)
        {
            // to ensure "dek" is required (not null)
            if (dek == null)
            {
                throw new ArgumentNullException("dek is a required property for StartFileScanInput and cannot be null");
            }
            this.Dek = dek;
        }

        /// <summary>
        /// A base64 encoded data encryption key, encrypted using VFS public key. This is important as this is used when starting document scan and also while uploading the file to s3
        /// </summary>
        /// <value>A base64 encoded data encryption key, encrypted using VFS public key. This is important as this is used when starting document scan and also while uploading the file to s3</value>
        [DataMember(Name = "dek", IsRequired = true, EmitDefaultValue = true)]
        public string Dek { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StartFileScanInput {\n");
            sb.Append("  Dek: ").Append(Dek).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
