/*
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using AffinidiTdk.WalletsClient.Client;
using AffinidiTdk.WalletsClient.Model;

namespace AffinidiTdk.WalletsClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRevocationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get revocation status list as RevocationListCredential
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <returns>GetRevocationListCredentialResultDto</returns>
        GetRevocationListCredentialResultDto GetRevocationCredentialStatus(string projectId, string walletId, string statusId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get revocation status list as RevocationListCredential
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <returns>ApiResponse of GetRevocationListCredentialResultDto</returns>
        ApiResponse<GetRevocationListCredentialResultDto> GetRevocationCredentialStatusWithHttpInfo(string projectId, string walletId, string statusId);
        /// <summary>
        /// Return revocation list credential.
        /// </summary>
        /// <remarks>
        /// Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <returns>GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        GetRevocationListCredentialResultDto GetRevocationListCredential(string listId, string walletId);

        /// <summary>
        /// Return revocation list credential.
        /// </summary>
        /// <remarks>
        /// Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <returns>ApiResponse of GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        ApiResponse<GetRevocationListCredentialResultDto> GetRevocationListCredentialWithHttpInfo(string listId, string walletId);
        /// <summary>
        /// Revoke Credential.
        /// </summary>
        /// <remarks>
        /// Update index/credetial at appropriate revocation list (set revoken is true).
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <returns></returns>
        void RevokeCredential(string walletId, RevokeCredentialInput revokeCredentialInput);

        /// <summary>
        /// Revoke Credential.
        /// </summary>
        /// <remarks>
        /// Update index/credetial at appropriate revocation list (set revoken is true).
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RevokeCredentialWithHttpInfo(string walletId, RevokeCredentialInput revokeCredentialInput);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRevocationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get revocation status list as RevocationListCredential
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRevocationListCredentialResultDto</returns>
        System.Threading.Tasks.Task<GetRevocationListCredentialResultDto> GetRevocationCredentialStatusAsync(string projectId, string walletId, string statusId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get revocation status list as RevocationListCredential
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRevocationListCredentialResultDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetRevocationListCredentialResultDto>> GetRevocationCredentialStatusWithHttpInfoAsync(string projectId, string walletId, string statusId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Return revocation list credential.
        /// </summary>
        /// <remarks>
        /// Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        System.Threading.Tasks.Task<GetRevocationListCredentialResultDto> GetRevocationListCredentialAsync(string listId, string walletId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Return revocation list credential.
        /// </summary>
        /// <remarks>
        /// Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRevocationListCredentialResultDto)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<GetRevocationListCredentialResultDto>> GetRevocationListCredentialWithHttpInfoAsync(string listId, string walletId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Revoke Credential.
        /// </summary>
        /// <remarks>
        /// Update index/credetial at appropriate revocation list (set revoken is true).
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RevokeCredentialAsync(string walletId, RevokeCredentialInput revokeCredentialInput, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revoke Credential.
        /// </summary>
        /// <remarks>
        /// Update index/credetial at appropriate revocation list (set revoken is true).
        /// </remarks>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RevokeCredentialWithHttpInfoAsync(string walletId, RevokeCredentialInput revokeCredentialInput, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRevocationApi : IRevocationApiSync, IRevocationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RevocationApi : IDisposable, IRevocationApi
    {
        private AffinidiTdk.WalletsClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public RevocationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public RevocationApi(string basePath)
        {
            this.Configuration = AffinidiTdk.WalletsClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.WalletsClient.Client.GlobalConfiguration.Instance,
                new AffinidiTdk.WalletsClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AffinidiTdk.WalletsClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AffinidiTdk.WalletsClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public RevocationApi(AffinidiTdk.WalletsClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AffinidiTdk.WalletsClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.WalletsClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AffinidiTdk.WalletsClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AffinidiTdk.WalletsClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RevocationApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RevocationApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AffinidiTdk.WalletsClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.WalletsClient.Client.GlobalConfiguration.Instance,
                new AffinidiTdk.WalletsClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AffinidiTdk.WalletsClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AffinidiTdk.WalletsClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RevocationApi(HttpClient client, AffinidiTdk.WalletsClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AffinidiTdk.WalletsClient.Client.Configuration.MergeConfigurations(
                AffinidiTdk.WalletsClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AffinidiTdk.WalletsClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AffinidiTdk.WalletsClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RevocationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public RevocationApi(AffinidiTdk.WalletsClient.Client.ISynchronousClient client, AffinidiTdk.WalletsClient.Client.IAsynchronousClient asyncClient, AffinidiTdk.WalletsClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AffinidiTdk.WalletsClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public AffinidiTdk.WalletsClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AffinidiTdk.WalletsClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AffinidiTdk.WalletsClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AffinidiTdk.WalletsClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AffinidiTdk.WalletsClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Get revocation status list as RevocationListCredential
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <returns>GetRevocationListCredentialResultDto</returns>
        public GetRevocationListCredentialResultDto GetRevocationCredentialStatus(string projectId, string walletId, string statusId)
        {
            AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> localVarResponse = GetRevocationCredentialStatusWithHttpInfo(projectId, walletId, statusId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get revocation status list as RevocationListCredential
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <returns>ApiResponse of GetRevocationListCredentialResultDto</returns>
        public AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> GetRevocationCredentialStatusWithHttpInfo(string projectId, string walletId, string statusId)
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'projectId' when calling RevocationApi->GetRevocationCredentialStatus");

            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->GetRevocationCredentialStatus");

            // verify the required parameter 'statusId' is set
            if (statusId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'statusId' when calling RevocationApi->GetRevocationCredentialStatus");

            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("projectId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter
            localVarRequestOptions.PathParameters.Add("statusId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(statusId)); // path parameter

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetRevocationListCredentialResultDto>("/v1/projects/{projectId}/wallets/{walletId}/revocation-statuses/{statusId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRevocationCredentialStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get revocation status list as RevocationListCredential
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRevocationListCredentialResultDto</returns>
        public async System.Threading.Tasks.Task<GetRevocationListCredentialResultDto> GetRevocationCredentialStatusAsync(string projectId, string walletId, string statusId, System.Threading.CancellationToken cancellationToken = default)
        {
            AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> localVarResponse = await GetRevocationCredentialStatusWithHttpInfoAsync(projectId, walletId, statusId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get revocation status list as RevocationListCredential
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Description for projectId.</param>
        /// <param name="walletId">Description for walletId.</param>
        /// <param name="statusId">Description for statusId.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRevocationListCredentialResultDto)</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto>> GetRevocationCredentialStatusWithHttpInfoAsync(string projectId, string walletId, string statusId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'projectId' is set
            if (projectId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'projectId' when calling RevocationApi->GetRevocationCredentialStatus");

            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->GetRevocationCredentialStatus");

            // verify the required parameter 'statusId' is set
            if (statusId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'statusId' when calling RevocationApi->GetRevocationCredentialStatus");


            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("projectId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(projectId)); // path parameter
            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter
            localVarRequestOptions.PathParameters.Add("statusId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(statusId)); // path parameter

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetRevocationListCredentialResultDto>("/v1/projects/{projectId}/wallets/{walletId}/revocation-statuses/{statusId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRevocationCredentialStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Return revocation list credential. Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <returns>GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        public GetRevocationListCredentialResultDto GetRevocationListCredential(string listId, string walletId)
        {
            AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> localVarResponse = GetRevocationListCredentialWithHttpInfo(listId, walletId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Return revocation list credential. Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <returns>ApiResponse of GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        public AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> GetRevocationListCredentialWithHttpInfo(string listId, string walletId)
        {
            // verify the required parameter 'listId' is set
            if (listId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'listId' when calling RevocationApi->GetRevocationListCredential");

            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->GetRevocationListCredential");

            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("listId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(listId)); // path parameter
            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetRevocationListCredentialResultDto>("/v1/wallets/{walletId}/revocation-list/{listId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRevocationListCredential", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Return revocation list credential. Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRevocationListCredentialResultDto</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<GetRevocationListCredentialResultDto> GetRevocationListCredentialAsync(string listId, string walletId, System.Threading.CancellationToken cancellationToken = default)
        {
            AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto> localVarResponse = await GetRevocationListCredentialWithHttpInfoAsync(listId, walletId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Return revocation list credential. Get revocation list 2020 Credential (required to check if VC revoked). It is a public endpoint.
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listId"></param>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRevocationListCredentialResultDto)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AffinidiTdk.WalletsClient.Client.ApiResponse<GetRevocationListCredentialResultDto>> GetRevocationListCredentialWithHttpInfoAsync(string listId, string walletId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'listId' is set
            if (listId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'listId' when calling RevocationApi->GetRevocationListCredential");

            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->GetRevocationListCredential");


            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("listId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(listId)); // path parameter
            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetRevocationListCredentialResultDto>("/v1/wallets/{walletId}/revocation-list/{listId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRevocationListCredential", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke Credential. Update index/credetial at appropriate revocation list (set revoken is true).
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <returns></returns>
        public void RevokeCredential(string walletId, RevokeCredentialInput revokeCredentialInput)
        {
            RevokeCredentialWithHttpInfo(walletId, revokeCredentialInput);
        }

        /// <summary>
        /// Revoke Credential. Update index/credetial at appropriate revocation list (set revoken is true).
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AffinidiTdk.WalletsClient.Client.ApiResponse<Object> RevokeCredentialWithHttpInfo(string walletId, RevokeCredentialInput revokeCredentialInput)
        {
            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->RevokeCredential");

            // verify the required parameter 'revokeCredentialInput' is set
            if (revokeCredentialInput == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'revokeCredentialInput' when calling RevocationApi->RevokeCredential");

            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter
            localVarRequestOptions.Data = revokeCredentialInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/wallets/{walletId}/revoke", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeCredential", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke Credential. Update index/credetial at appropriate revocation list (set revoken is true).
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RevokeCredentialAsync(string walletId, RevokeCredentialInput revokeCredentialInput, System.Threading.CancellationToken cancellationToken = default)
        {
            await RevokeCredentialWithHttpInfoAsync(walletId, revokeCredentialInput, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Revoke Credential. Update index/credetial at appropriate revocation list (set revoken is true).
        /// </summary>
        /// <exception cref="AffinidiTdk.WalletsClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId">id of the wallet</param>
        /// <param name="revokeCredentialInput">RevokeCredential</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AffinidiTdk.WalletsClient.Client.ApiResponse<Object>> RevokeCredentialWithHttpInfoAsync(string walletId, RevokeCredentialInput revokeCredentialInput, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'walletId' is set
            if (walletId == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'walletId' when calling RevocationApi->RevokeCredential");

            // verify the required parameter 'revokeCredentialInput' is set
            if (revokeCredentialInput == null)
                throw new AffinidiTdk.WalletsClient.Client.ApiException(400, "Missing required parameter 'revokeCredentialInput' when calling RevocationApi->RevokeCredential");


            AffinidiTdk.WalletsClient.Client.RequestOptions localVarRequestOptions = new AffinidiTdk.WalletsClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AffinidiTdk.WalletsClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("walletId", AffinidiTdk.WalletsClient.Client.ClientUtils.ParameterToString(walletId)); // path parameter
            localVarRequestOptions.Data = revokeCredentialInput;

            // authentication (ProjectTokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", this.Configuration.GetApiKeyWithPrefix("authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/wallets/{walletId}/revoke", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeCredential", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
