/*
 * OidcVpAdapterBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.LoginConfigurationClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.LoginConfigurationClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.LoginConfigurationClient.Model
{
    /// <summary>
    /// CorsLoginSessionAcceptResponseOK
    /// </summary>
    [DataContract(Name = "CorsLoginSessionAcceptResponseOK")]
    public partial class CorsLoginSessionAcceptResponseOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorsLoginSessionAcceptResponseOK" /> class.
        /// </summary>
        /// <param name="corsLoginSessionAcceptResponseOk">corsLoginSessionAcceptResponseOk.</param>
        public CorsLoginSessionAcceptResponseOK(string corsLoginSessionAcceptResponseOk = default)
        {
            this.CorsLoginSessionAcceptResponseOk = corsLoginSessionAcceptResponseOk;
        }

        /// <summary>
        /// Gets or Sets CorsLoginSessionAcceptResponseOk
        /// </summary>
        [DataMember(Name = "corsLoginSessionAcceptResponseOk", EmitDefaultValue = false)]
        public string CorsLoginSessionAcceptResponseOk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CorsLoginSessionAcceptResponseOK {\n");
            sb.Append("  CorsLoginSessionAcceptResponseOk: ").Append(CorsLoginSessionAcceptResponseOk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
