/*
 * IotaService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AffinidiTdk.IotaClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.IotaClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.IotaClient.Model
{
    /// <summary>
    /// CorsFetchIotaVpResponseOK
    /// </summary>
    [DataContract(Name = "CorsFetchIotaVpResponseOK")]
    public partial class CorsFetchIotaVpResponseOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorsFetchIotaVpResponseOK" /> class.
        /// </summary>
        /// <param name="corsFetchIotaVpResponseOk">corsFetchIotaVpResponseOk.</param>
        public CorsFetchIotaVpResponseOK(string corsFetchIotaVpResponseOk = default)
        {
            this.CorsFetchIotaVpResponseOk = corsFetchIotaVpResponseOk;
        }

        /// <summary>
        /// Gets or Sets CorsFetchIotaVpResponseOk
        /// </summary>
        [DataMember(Name = "corsFetchIotaVpResponseOk", EmitDefaultValue = false)]
        public string CorsFetchIotaVpResponseOk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CorsFetchIotaVpResponseOK {\n");
            sb.Append("  CorsFetchIotaVpResponseOk: ").Append(CorsFetchIotaVpResponseOk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
