/*
 * IotaService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.IotaClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.IotaClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.IotaClient.Model
{
    /// <summary>
    /// ListLoggedConsentsOK
    /// </summary>
    [DataContract(Name = "ListLoggedConsentsOK")]
    public partial class ListLoggedConsentsOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListLoggedConsentsOK" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListLoggedConsentsOK() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListLoggedConsentsOK" /> class.
        /// </summary>
        /// <param name="consents">consents (required).</param>
        /// <param name="lastEvaluatedKey">lastEvaluatedKey.</param>
        public ListLoggedConsentsOK(List<ConsentDto> consents = default, string lastEvaluatedKey = default)
        {
            // to ensure "consents" is required (not null)
            if (consents == null)
            {
                throw new ArgumentNullException("consents is a required property for ListLoggedConsentsOK and cannot be null");
            }
            this.Consents = consents;
            this.LastEvaluatedKey = lastEvaluatedKey;
        }

        /// <summary>
        /// Gets or Sets Consents
        /// </summary>
        [DataMember(Name = "consents", IsRequired = true, EmitDefaultValue = true)]
        public List<ConsentDto> Consents { get; set; }

        /// <summary>
        /// Gets or Sets LastEvaluatedKey
        /// </summary>
        [DataMember(Name = "lastEvaluatedKey", EmitDefaultValue = false)]
        public string LastEvaluatedKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListLoggedConsentsOK {\n");
            sb.Append("  Consents: ").Append(Consents).Append("\n");
            sb.Append("  LastEvaluatedKey: ").Append(LastEvaluatedKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
