/*
 * IotaService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AffinidiTdk.IotaClient.Client.FileParameter;
using OpenAPIDateConverter = AffinidiTdk.IotaClient.Client.OpenAPIDateConverter;

namespace AffinidiTdk.IotaClient.Model
{
    /// <summary>
    /// ListDcqlQueriesOK
    /// </summary>
    [DataContract(Name = "ListDcqlQueriesOK")]
    public partial class ListDcqlQueriesOK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDcqlQueriesOK" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListDcqlQueriesOK() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListDcqlQueriesOK" /> class.
        /// </summary>
        /// <param name="dcqlQueries">dcqlQueries (required).</param>
        /// <param name="lastEvaluatedKey">lastEvaluatedKey.</param>
        public ListDcqlQueriesOK(List<DcqlQueryDto> dcqlQueries = default, string lastEvaluatedKey = default)
        {
            // to ensure "dcqlQueries" is required (not null)
            if (dcqlQueries == null)
            {
                throw new ArgumentNullException("dcqlQueries is a required property for ListDcqlQueriesOK and cannot be null");
            }
            this.DcqlQueries = dcqlQueries;
            this.LastEvaluatedKey = lastEvaluatedKey;
        }

        /// <summary>
        /// Gets or Sets DcqlQueries
        /// </summary>
        [DataMember(Name = "dcqlQueries", IsRequired = true, EmitDefaultValue = true)]
        public List<DcqlQueryDto> DcqlQueries { get; set; }

        /// <summary>
        /// Gets or Sets LastEvaluatedKey
        /// </summary>
        [DataMember(Name = "lastEvaluatedKey", EmitDefaultValue = false)]
        public string LastEvaluatedKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListDcqlQueriesOK {\n");
            sb.Append("  DcqlQueries: ").Append(DcqlQueries).Append("\n");
            sb.Append("  LastEvaluatedKey: ").Append(LastEvaluatedKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
